# Generated by Django 4.1.6 on 2023-08-13 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_buyer_alter_brand_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='username',
            field=models.CharField(default='', max_length=25),
        ),
    ]
